### ISSUE TITLE
Find a suitable website template

### ISSUE THREAD

**Issue by pesehr** [AoLab/AoLab.github.io#2]
These websites are good examples. Please add more interesting websites below this comment. 
- https://www.iot-lab.ch/
- https://www.media.mit.edu/research/
- https://design.mit.ed
- https://jhdavislab.org

**Comment by 1995parham** [comment]
what do you think about a simple single page theme like [I1820 Website](ihttps://1820.github.io)?

**Comment by pesehr** [comment]
Negative

**Comment by 1995parham** [comment]
Ok, so we need a website with multipage that supports blogging. Am I right?

**Comment by pesehr** [comment]
Take a look at the examples.

**Comment by 1995parham** [comment]
I like the Davis lab website and I think it is a multipage website. Davis lab has a new design, unlike the others that have an old design.
